replicaCount: 2

image:
  repository: danielshmatnik/backend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5001

mysql:
  host: mysqldb
  password: "123456"

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"
